anchors: 64
annotations_path: /data3/bhkim/datasets/OSDaR23_rgb_center_jpg/egopath_labels.json
backbone: efficientnet-b3
base_model: chromatic-laughter-5
batch_size: 32
brightness: 0.5
contrast: 0.5
crop_margin_sides: 0.1
crop_margin_top: 0.1
epochs: 300
fc_hidden_size: 2048
freeze_base: true
gpu_preprocess: false
hue: 0.2
images_path: /data3/bhkim/datasets/OSDaR23_rgb_center_jpg
input_shape:
- 3
- 512
- 512
learning_rate: 0.0001
method: regression
optimizer: adam
perspective_weight_limit_percentile: 95
pool_channels: 8
pretrained: true
real_sequences: true
rnn_hidden: 256
rnn_layers: 1
saturation: 0.5
scheduler: one_cycle
seed: 42
seg_rnn_hidden: 8
seq_jitter: 0.05
seq_len: 5
seq_occlusion_max: 0.4
seq_occlusion_min: 0.1
seq_occlusion_prob: 0.5
seq_stride: 3
std_dev_factor_sides: 0.3
std_dev_factor_top: 0.1
temporal: true
test_iterations: 10
test_prop: 0.1
train_prop: 0.8
val_iterations: 1
val_prop: 0.1
workers: 16
ylimit_loss_weight: 0.5
